channels:
  - conda-forge
dependencies:
  - appmode
  - tensorflow=2.15
  - numpy>=1.14.5
  - h5py>=2.10.0
  - ipywidgets=7.5.1
  - pillow>=8.3.2
  - joblib>=0.14.1
  - statsmodels>=0.11.0
  - plotly=4.7.1
